services:
  - type: web
    name: movie-master
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    branch: main
    # Specify Node.js version
    envVars:
      - key: NODE_VERSION
        value: 18.20.8
